const state={token:localStorage.getItem('ffToken')||'',user:null,scores:[],charities:[],plan:'monthly',metrics:null,authMode:'signup'};
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const authModal=$('#authModal'),appShell=$('#appShell');
async function api(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(state.token)headers.Authorization=`Bearer ${state.token}`;const response=await fetch(path,{...options,headers});const data=await response.json();if(!response.ok)throw new Error(data.error||'Request failed');return data}
async function hydrate(){const [me,scores,charities]=await Promise.all([api('/api/me'),api('/api/scores'),api('/api/charities')]);state.user=me.user;state.scores=scores.scores;state.charities=charities.charities;state.plan=state.user.plan;$('#userName').textContent=state.user.name;$('#userMeta').textContent=`${state.user.role==='admin'?'Administrator':'Member'} · ${state.user.plan} plan`}
function openAuth(mode='signup'){state.authMode=mode;$('#modalTitle').innerHTML=mode==='login'?'Welcome back.<br><i>Keep playing.</i>':'Start playing<br><i>with purpose.</i>';$('#authSubmit').innerHTML=mode==='login'?'Log in <span>↗</span>':'Create my account <span>↗</span>';authModal.classList.add('open');authModal.setAttribute('aria-hidden','false')}
function closeAuth(){authModal.classList.remove('open');authModal.setAttribute('aria-hidden','true')}
['#joinBtn','#heroJoin','#finalJoin'].forEach(id=>$(id).addEventListener('click',()=>openAuth('signup')));$('#loginBtn').addEventListener('click',()=>openAuth('login'));$$('[data-close]').forEach(b=>b.addEventListener('click',closeAuth));authModal.addEventListener('click',e=>{if(e.target===authModal)closeAuth()});
$$('[data-plan]').forEach(button=>button.addEventListener('click',()=>{$$('[data-plan]').forEach(b=>b.classList.remove('active'));button.classList.add('active');state.plan=button.dataset.plan}));
$('#authSubmit').addEventListener('click',async()=>{const email=$('#emailInput').value.trim();const password=$('#passwordInput').value;if(!email.includes('@')||password.length<8){alert('Please enter a valid email and a password of at least 8 characters.');return}try{const result=await api(`/api/auth/${state.authMode}`,{method:'POST',body:JSON.stringify({email,password,plan:state.plan})});state.token=result.token;localStorage.setItem('ffToken',state.token);await hydrate();closeAuth();openApp('overview')}catch(error){alert(error.message)}});
async function startSession(){if(!state.token)return;try{await hydrate();openApp('overview')}catch{localStorage.removeItem('ffToken');state.token=''}}
function openApp(view){appShell.classList.add('open');appShell.setAttribute('aria-hidden','false');renderView(view)}
function closeApp(){appShell.classList.remove('open');appShell.setAttribute('aria-hidden','true')}
$('#closeApp').addEventListener('click',closeApp);$('#logoutBtn').addEventListener('click',()=>{localStorage.removeItem('ffToken');state.token='';state.user=null;closeApp()});$$('.app-nav button').forEach(button=>button.addEventListener('click',()=>renderView(button.dataset.view)));
function renderView(view){$$('.app-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const titles={overview:['MEMBER OVERVIEW',`Good morning, ${state.user?.name?.split(' ')[0]||'Jamie'}.`],scores:['SCOREBOOK','Your latest five scores.'],charity:['YOUR CAUSE','Impact, made personal.'],draws:['DRAWS & WINNINGS','Your place in the moment.'],admin:['ADMIN CONTROL','The whole picture.']};$('#viewKicker').textContent=titles[view][0];$('#viewTitle').textContent=titles[view][1];const views={overview:overviewView,scores:scoresView,charity:charityView,draws:drawsView,admin:adminView};$('#viewContainer').innerHTML=views[view]();bindView(view)}
function overviewView(){return `<div class="dashboard-grid"><div class="dash-card balance-card"><span>CHARITY CONTRIBUTION THIS YEAR</span><strong>£74.40</strong><span>to ${state.user?.charity||'Mindful Miles'}</span><div class="impact-meter"><i></i></div><small>You've made 63% more impact than the average member.</small></div><div class="dash-card draw-card"><h3>Next draw <a href="#" data-view-link="draws">View all ↗</a></h3><div class="upcoming"><div class="calendar">30</div><div><strong>April community draw</strong><span>2,480 players · 14 days left</span></div></div><div class="winner-banner">✦ <strong>Jackpot is up to £12,640</strong><br><span>Every active subscription gets a line.</span></div></div><div class="dash-card score-preview"><h3>Recent scores <a href="#" data-view-link="scores">Edit scores ↗</a></h3><div class="score-list">${state.scores.slice(0,5).map(s=>`<div class="score-tile"><strong>${s.score}</strong><small>${formatDate(s.date)}</small></div>`).join('')}</div></div></div>`}
function scoresView(){return `<div class="view-panel"><h3>Add a score</h3><div class="score-form"><label>Stableford score<input type="number" id="scoreInput" min="1" max="45" placeholder="1 - 45"></label><label>Round date<input type="date" id="dateInput" max="2026-12-31"></label><button class="button button-dark" id="addScore">Add score <span>+</span></button></div><p class="form-note">Scores are kept newest first. A maximum of five scores is retained, with one score allowed per date.</p></div><div class="view-panel"><h3>Your scorebook <span class="form-note">${state.scores.length}/5 scores</span></h3><table class="scores-table"><thead><tr><th>Score</th><th>Date</th><th></th></tr></thead><tbody>${state.scores.map(s=>`<tr><td><strong>${s.score}</strong></td><td>${formatDate(s.date)}</td><td><button class="danger-link" data-delete-score="${s.id}">Delete</button></td></tr>`).join('')}</tbody></table></div>`}
function charityView(){return `<div class="view-panel"><h3>Your monthly contribution</h3><div class="impact-meter"><i style="width:${state.user?.contributionPercent*2||20}%"></i></div><p class="form-note">You're giving <strong>${state.plan==='yearly'?'£10.00':'£6.20'}</strong> a month through your ${state.plan} membership. You can increase this at any time.</p><label>Contribution percentage<input type="range" id="contributionRange" min="10" max="50" value="${state.user?.contributionPercent||10}" style="width:100%"></label></div><div class="view-panel"><h3>Choose your cause</h3><div class="charity-options">${state.charities.map(o=>`<button class="charity-option ${state.user?.charity===o.name?'selected':''}" data-charity="${o.name}"><strong>${o.name}</strong><small>${o.description}</small></button>`).join('')}</div></div>`}
function drawsView(){return `<div class="dashboard-grid"><div class="dash-card balance-card"><span>TOTAL WINNINGS</span><strong>£0.00</strong><span>Keep playing, Jamie.</span></div><div class="dash-card"><h3>Participation</h3><div class="upcoming"><div class="calendar">12</div><div><strong>Draws entered</strong><span>Since joining</span></div></div></div><div class="view-panel score-preview"><h3>Prize pool breakdown</h3><table class="scores-table"><tbody><tr><td>5-number jackpot</td><td><strong>40%</strong></td><td>£12,640</td></tr><tr><td>4-number match</td><td><strong>35%</strong></td><td>£4,180</td></tr><tr><td>3-number match</td><td><strong>25%</strong></td><td>£2,980</td></tr></tbody></table></div></div>`}
function adminView(){const metrics=state.metrics||{activeUsers:'—',prizePool:'—',charityTotal:'—',pendingReviews:'—'};return `<div class="admin-metrics"><div class="metric"><span>ACTIVE USERS</span><strong>${metrics.activeUsers}</strong></div><div class="metric"><span>PRIZE POOL</span><strong>${metrics.prizePool}</strong></div><div class="metric"><span>CHARITY TOTAL</span><strong>${metrics.charityTotal}</strong></div><div class="metric"><span>PENDING REVIEWS</span><strong>${metrics.pendingReviews}</strong></div></div><div class="view-panel" style="margin-top:20px"><div class="admin-tabs"><button class="active">Draw control</button><button>Winner verification</button><button>Charities</button></div><h3>April draw configuration</h3><p class="form-note">Run a simulation before publishing results. The current draw is scheduled for 30 April 2026.</p><button class="button button-dark" id="simulateDraw">Run simulation <span>↗</span></button><div id="simulationResult"></div></div>`}
async function bindView(view){$$('[data-view-link]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();renderView(a.dataset.viewLink)}));if(view==='scores'){$('#addScore').addEventListener('click',addScore);$$('[data-delete-score]').forEach(b=>b.addEventListener('click',async()=>{try{await api(`/api/scores/${b.dataset.deleteScore}`,{method:'DELETE'});state.scores=(await api('/api/scores')).scores;renderView('scores')}catch(error){alert(error.message)}}))}if(view==='charity'){ $$('[data-charity]').forEach(b=>b.addEventListener('click',async()=>{try{const result=await api('/api/profile',{method:'PUT',body:JSON.stringify({charity:b.dataset.charity})});state.user=result.user;renderView('charity')}catch(error){alert(error.message)}}));$('#contributionRange').addEventListener('change',async event=>{const result=await api('/api/profile',{method:'PUT',body:JSON.stringify({contributionPercent:event.target.value})});state.user=result.user;renderView('charity')})}if(view==='admin'){if(!state.metrics){try{state.metrics=(await api('/api/admin/metrics')).metrics;renderView('admin');return}catch(error){$('#viewContainer').insertAdjacentHTML('beforeend',`<div class="winner-banner">${error.message}</div>`);return}}$('#simulateDraw').addEventListener('click',async()=>{try{const result=await api('/api/admin/draws/simulate',{method:'POST'});$('#simulationResult').innerHTML=`<div class="winner-banner">${result.result}</div>`}catch(error){alert(error.message)}})}}
async function addScore(){const score=Number($('#scoreInput').value);const date=$('#dateInput').value;if(!score||score<1||score>45||!date){alert('Enter a score from 1 to 45 and a round date.');return}try{state.scores=(await api('/api/scores',{method:'POST',body:JSON.stringify({score,date})})).scores;renderView('scores')}catch(error){alert(error.message)}}
function formatDate(value){return new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(`${value}T12:00:00`))}
$('#exploreBtn').addEventListener('click',()=>document.querySelector('#charities').scrollIntoView({behavior:'smooth'}));$('#seeDrawBtn').addEventListener('click',()=>document.querySelector('#draw').scrollIntoView({behavior:'smooth'}));
startSession();
